server:
  port: 8089
  servlet:
    context-path: /springboot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+0
    serialization:
      write-dates-as-timestamps: false

  thymeleaf:
    prefix: classpath:/templates/